### ISSUE TITLE
Thoughts on providing dispatch and the current action as arguments to the errorHandler?

### ISSUE THREAD

**Issue by willmorgan** [sergiodxa/redux-catch#4]
This looks like a really useful tool for catching and logging errors inside reducers.

I'm just wondering if it breaks convention massively if the errorHandler function were able to dispatch an action that the app could pick up - like displaying a warning, or so on?

Something along the lines of this:

```js
import reduxCatch from 'redux-catch';
const errorHandler = (error, getState, dispatch, lastAction) => {
    console.error(error);
    dispatch({
        type: APP_UNKNOWN_ERROR,
        payload: {
            lastAction
        }
    });
};
const middleware = [reduxCatch(errorHandler)];
return createStore(
    rootReducer,
    initialState,
    compose(
        applyMiddleware(...middleware),
    )
); 
```

Thanks for writing this middleware!

**Comment by sergiodxa** [comment]
I love the idea, I just leave you a message in the PR, but I'm going to merge this.
